version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /home/ec2-user/grafana-server/grafana-storage:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"  
    restart: unless-stopped
    depends_on:
      - mysql

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /home/ec2-user/grafana-server/influxdb-storage:/var/lib/influxdb
    environment:
      INFLUXDB_ADMIN_USER: "admin"  
      INFLUXDB_ADMIN_PASSWORD: "admin"  
      INFLUXDB_DB: "mydb"  
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"  
      MYSQL_DATABASE: "grafana_db"  
      MYSQL_USER: "grafana_user"  
      MYSQL_PASSWORD: "grafana_password" 
    ports:
      - "3306:3306"
    volumes:
      - /home/ec2-user/grafana-server/mysql-storage:/var/lib/mysql
    restart: unless-stopped
